[workspace]
resolver = "2"
members = ["crates/tf-term", "crates/tf-proto", "apps/cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/zent7x/terminal-fenster"

[workspace.dependencies]
libc = "0.2"
flate2 = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "unwind" # we MUST run our terminal-restore panic hook; abort would corrupt the tty
